# Intro to Agent Chat API with First Assistant Agent
Notebook focuses on creating an agent using the `Assistant Agent` API

In [2]:
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.openai import OpenAIChatCompletionClient
from dotenv import load_dotenv
import os

load_dotenv()
api_key = os.getenv('OPENAI_API_KEY')
#print(f"API KEY: {api_key}")

In [3]:
# Load the "brain"
model_client = OpenAIChatCompletionClient(model = 'gpt-4o', api_key=api_key)

# Create First Assistant AGent
The `Assistant Agent` is a a versatile agent for conversions, powered by AgentChat

In [4]:
assistant = AssistantAgent(name = "assistant",model_client=model_client,description='A basic first agent')

# Test the Assistant Agent

In [6]:
result = await assistant.run(task="what's the capital of France ?")
print(result)

messages=[TextMessage(id='b31a9bb7-2200-4d24-bbcb-fb19afd80983', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 50, 599429, tzinfo=datetime.timezone.utc), content="what's the capital of France ?", type='TextMessage'), TextMessage(id='d4dcc146-4ca1-494c-96cb-08fb03b283a7', source='assistant', models_usage=RequestUsage(prompt_tokens=55, completion_tokens=9), metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 52, 476038, tzinfo=datetime.timezone.utc), content='The capital of France is Paris. TERMINATE', type='TextMessage')] stop_reason=None


messages=[TextMessage(id='b31a9bb7-2200-4d24-bbcb-fb19afd80983', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 50, 599429, tzinfo=datetime.timezone.utc), content="what's the capital of France ?", type='TextMessage'), TextMessage(id='d4dcc146-4ca1-494c-96cb-08fb03b283a7', source='assistant', models_usage=RequestUsage(prompt_tokens=55, completion_tokens=9), metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 52, 476038, tzinfo=datetime.timezone.utc), content='The capital of France is Paris. TERMINATE', type='TextMessage')] stop_reason=None

In [7]:
print(result.messages)

[TextMessage(id='b31a9bb7-2200-4d24-bbcb-fb19afd80983', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 50, 599429, tzinfo=datetime.timezone.utc), content="what's the capital of France ?", type='TextMessage'), TextMessage(id='d4dcc146-4ca1-494c-96cb-08fb03b283a7', source='assistant', models_usage=RequestUsage(prompt_tokens=55, completion_tokens=9), metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 14, 52, 476038, tzinfo=datetime.timezone.utc), content='The capital of France is Paris. TERMINATE', type='TextMessage')]


In [ ]:
# Get the last message and get the contents
print(result.messages[-1].content)

The capital of France is Paris. TERMINATE


In [9]:
result = await assistant.run(task="what's the capital of USA and write some more about the same ?")
print(result)

messages=[TextMessage(id='644b7f52-960e-4f5d-bf7c-3bfc9361cd7a', source='user', models_usage=None, metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 19, 13, 786588, tzinfo=datetime.timezone.utc), content="what's the capital of USA and write some more about the same ?", type='TextMessage'), TextMessage(id='40173f6e-3e57-4b42-ad43-c33ac5ebec58', source='assistant', models_usage=RequestUsage(prompt_tokens=87, completion_tokens=219), metadata={}, created_at=datetime.datetime(2026, 1, 21, 16, 19, 20, 351230, tzinfo=datetime.timezone.utc), content='The capital of the United States is Washington, D.C. Washington, D.C., officially known as the District of Columbia, is not part of any U.S. state and is directly governed by the federal government. The city was founded on July 16, 1790, named after George Washington, the first President of the United States, and "Columbia," a poetic name for America derived from Christopher Columbus.\n\nWashington, D.C. serves as the seat of the U.S. gov

In [10]:
print(result.messages[-1].content)

The capital of the United States is Washington, D.C. Washington, D.C., officially known as the District of Columbia, is not part of any U.S. state and is directly governed by the federal government. The city was founded on July 16, 1790, named after George Washington, the first President of the United States, and "Columbia," a poetic name for America derived from Christopher Columbus.

Washington, D.C. serves as the seat of the U.S. government and hosts all three branches: the legislative (Congress), the executive (the President), and the judicial (the Supreme Court). The city is well known for its historic landmarks and monuments, such as the U.S. Capitol, the White House, the Washington Monument, and the Lincoln Memorial. Additionally, it's home to the Smithsonian Institution, which encompasses several museums and galleries.

As a political and cultural city, Washington, D.C. attracts millions of tourists every year. The capital also plays a crucial role in international diplomacy, h